// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PayrollService.DataAccess.Contexts;

namespace PayrollService.DataAccess.Migrations
{
    [DbContext(typeof(PayrollDatabaseContext))]
    partial class PayrollDatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("PayrollService.Model.Models.Dto.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmployeeType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("IdentityNumber")
                        .HasColumnType("bigint");

                    b.Property<string>("Mail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmployeeId");

                    b.ToTable("Employee");
                });

            modelBuilder.Entity("PayrollService.Model.Models.Dto.EmployeeSalaryDetails", b =>
                {
                    b.Property<int>("EmployeeSalaryDetailsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<double>("BasicSalary")
                        .HasColumnType("float");

                    b.Property<double>("DailyFee")
                        .HasColumnType("float");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<double>("HourlyFee")
                        .HasColumnType("float");

                    b.Property<int>("SalaryMonth")
                        .HasColumnType("int");

                    b.Property<int>("SalaryYear")
                        .HasColumnType("int");

                    b.HasKey("EmployeeSalaryDetailsId");

                    b.ToTable("EmployeeSalaryDetail");
                });

            modelBuilder.Entity("PayrollService.Model.Models.Dto.EmployeeWorkingActivities", b =>
                {
                    b.Property<int>("EmployeeWorkingActivitiesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("TotalWorkedDayInMonth")
                        .HasColumnType("int");

                    b.Property<int>("TotalWorkedHoursInMonth")
                        .HasColumnType("int");

                    b.Property<int>("WorkedMonth")
                        .HasColumnType("int");

                    b.Property<int>("WorkedYear")
                        .HasColumnType("int");

                    b.HasKey("EmployeeWorkingActivitiesId");

                    b.ToTable("EmployeeWorkingActivity");
                });
#pragma warning restore 612, 618
        }
    }
}
